---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Pull image
      docker_image:
        name: bhavya0560/calcproj
        source: pull
    - name: deploy docker container
      docker_container:
        image: bhavya0560/calcproj
        name: container2
        state: started
        ports:
          - "8080:80"
